# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20181211_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nameD',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nameP',
            field=models.CharField(max_length=128),
        ),
    ]
